use_frameworks!

target 'ZMWebClient_Example' do
  pod 'ZMWebClient', :path => '../'

  target 'ZMWebClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
